name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
          IMAGE_TAG: ${{ github.sha }}
      run: |
          docker build . -t http://docker-registry.gruposalutem.com.br:5010/test:$IMAGE_TAG
          docker push http://docker-registry.gruposalutem.com.br:5010/test:$IMAGE_TAG
