name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Logando no Docker Registry do Github
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login https://docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Declarando algumas variáveis
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=tag;]$(echo ${GITHUB_REF/refs\/tags\//})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Imprimindo variáveis
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Tag: ${{ steps.vars.outputs.tag }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"

      - name: Criando Imagem do Docker
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/guilhermestella/action-test/action-test:${GITHUB_SHA::8}

      # Push Image to Registry
      - name: Push the tagged Docker image
        run: docker push docker.pkg.github.com/guilhermestella/action-test/action-test:${GITHUB_SHA::8}
