name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      # Get Project Version
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # Create image tagged with project version
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag guilhermestella/action-test:${{steps.vars.outputs.tag}}

      # Push Image to Registry
      - name: Push the tagged Docker image
        run: docker push guilhermestella/action-test:${{steps.vars.outputs.tag}}
